### ISSUE TITLE
Phonegap-googlemaps-plugin with $ionicModal

### ISSUE THREAD

**Issue by procom** [wf9a5m75/ionic_test#3]
Hello,

I would like to integrate phonegap-googlemaps-plugin into $ionicModal.

It works when I show map into view but not into modal.

Background of modal becomes transparent and map don't show.

**Comment by wf9a5m75** [comment]
The map displays under the browser.
So you can not put the map on the modal window.
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Map#how-does-the-plugin-work
